subpackage:
  - runtime*
name: carnotzet+os-contelia-rpiz2w
version: 0.12.0
$version: 0.12.0
distribution: raspberry/
maintainer:
  name: Mathieu Schroeter
  email: schroeter@epsitec.ch
architecture:
  - source
description:
  brief: Carnotzet Contelia Operating System
  long: ''
dependency:
  install:
    carnotzet+os-base-contelia-rpiz2w:
      - version: ''
        architecture: []
  build:
    tytso+e2fsprogs:
      - version: ''
        architecture: []
    linux+util-linux:
      - version: ''
        architecture: []
    gnu+mtools:
      - version: ''
        architecture: []
    e2tools+e2tools:
      - version: ''
        architecture: []
    debian+fakeroot:
      - version: ''
        architecture: []
bump: []
data:
  get:
    uri: ''
    mirrors: []
    ref: ''
    $ref: ''
    out: ''
    externals: false
    prepare: ''
  type: src
  configure: ''
  rules:
    type: script
    location: ''
    args:
      postinst: ''
      prerm: ''
      makeall: |-
        const {genRoot, genImage} = imp('raspberry');

        yield cmd('pacman.syncRepository', {distribution: 'raspberry'});

        /* Generate the root for the MMC */
        yield genRoot('carnotzet', '<PEON.ASSETS.GLOBAL>', [
          'carnotzet+os-base-contelia-rpiz2w-x+bin'
        ]);

        yield genImage('carnotzet',
          '<PEON.INSTALLDIR>/opt/img/carnotzet-os-contelia-<THIS.$VERSION>-rpiz2w.img'
        );
      maketest: ''
      makeinstall: ''
    test: none
    env: {}
  deploy: ''
  env:
    path: []
    other: {}
  embedded: true
  runtime:
    configure: ''
