#!/bin/sh
exec 2>&1

echo "Mount Whispi Gadget..."

if [ -f /boot/carnotzet.cfg ]; then
  . /boot/carnotzet.cfg
else
  echo "Error: /boot/carnotzet.cfg not found"
  exit 1
fi

mount_gadget() {
  GADGET_DIR=/sys/kernel/config/usb_gadget/piwin

  mkdir -p "$GADGET_DIR"
  cd "$GADGET_DIR"

  if [ "$gadget_network_target_os" = "win" ]; then
    echo 0x2e8a > idVendor
    echo 0x0013 > idProduct
  else
    echo 0x1d6b > idVendor
    echo 0x0104 > idProduct
  fi

  echo 0x0200 > bcdUSB
  echo 0x0100 > bcdDevice

  mkdir -p strings/0x409
  echo "0123456789ABCDEF" > strings/0x409/serialnumber
  echo "Xcraft"           > strings/0x409/manufacturer
  echo "Whispi Audio"     > strings/0x409/product

  echo 0xEF > bDeviceClass
  echo 0x02 > bDeviceSubClass
  echo 0x01 > bDeviceProtocol

  mkdir -p configs/c.1/strings/0x409
  echo 250 > configs/c.1/MaxPower

  if [ "$gadget_network_target_os" = "win" ]; then
    echo "RNDIS + UAC2" > configs/c.1/strings/0x409/configuration

    mkdir -p os_desc
    echo 1       > os_desc/use
    echo 0xcd    > os_desc/b_vendor_code
    echo MSFT100 > os_desc/qw_sign

    mkdir -p functions/rndis.usb0
    echo "02:1A:11:00:00:11" > functions/rndis.usb0/dev_addr
    echo "02:1A:11:00:00:12" > functions/rndis.usb0/host_addr
    mkdir -p functions/rndis.usb0/os_desc/interface.rndis
    echo "RNDIS"   > functions/rndis.usb0/os_desc/interface.rndis/compatible_id
    echo "5162001" > functions/rndis.usb0/os_desc/interface.rndis/sub_compatible_id

    ln -s functions/rndis.usb0 configs/c.1/
  else
    echo "ECM + UAC2" > configs/c.1/strings/0x409/configuration

    mkdir -p functions/ecm.usb0
    echo "02:1A:11:00:00:01" > functions/ecm.usb0/dev_addr

    ln -s functions/ecm.usb0 configs/c.1/
  fi

  mkdir -p functions/uac2.usb0

  echo 0x3    > functions/uac2.usb0/c_chmask
  echo 48000  > functions/uac2.usb0/c_srate
  echo 2      > functions/uac2.usb0/c_ssize
  echo 1      > functions/uac2.usb0/c_mute_present
  echo 1      > functions/uac2.usb0/c_volume_present
  echo -10240 > functions/uac2.usb0/c_volume_min
  echo 0      > functions/uac2.usb0/c_volume_max
  echo 256    > functions/uac2.usb0/c_volume_res
  echo "Pi Headphones In" > functions/uac2.usb0/c_it_name
  echo "Pi Playback Out"  > functions/uac2.usb0/c_ot_name

  echo 0x1    > functions/uac2.usb0/p_chmask
  echo 48000  > functions/uac2.usb0/p_srate
  echo 2      > functions/uac2.usb0/p_ssize
  echo 1      > functions/uac2.usb0/p_mute_present
  echo 1      > functions/uac2.usb0/p_volume_present
  echo -10240 > functions/uac2.usb0/p_volume_min
  echo 0      > functions/uac2.usb0/p_volume_max
  echo 256    > functions/uac2.usb0/p_volume_res
  echo "Pi Mic In"      > functions/uac2.usb0/p_it_name
  echo "Pi Capture Out" > functions/uac2.usb0/p_ot_name

  echo "Pi Audio Bridge" > functions/uac2.usb0/function_name
  echo "Pi Clock In"     > functions/uac2.usb0/clksrc_in_name
  echo "Pi Clock Out"    > functions/uac2.usb0/clksrc_out_name

  ln -s functions/uac2.usb0 configs/c.1/

  if [ "$gadget_network_target_os" = "win" ]; then
    ln -s configs/c.1 os_desc
  fi

  UDC_NAME="$(ls /sys/class/udc | head -n 1)"
  echo "$UDC_NAME" > UDC

  # Wait for the new usb0 device and setup the IP address
  TIMEOUT=30
  while [ $TIMEOUT -gt 0 ]; do
    if ip -6 addr flush dev usb0 && \
       ip -6 addr add "fd66:66:66::1/64" dev usb0 && \
       ip link set usb0 up; then
      break
    fi

    sleep 0.5
    TIMEOUT=$((TIMEOUT - 1))
  done

  if [ $TIMEOUT -le 0 ]; then
    echo "Error: cannot configure usb0 after 30s"
    exit 1
  fi
}

dispose() {
  echo "Dispose..."
  # TODO: remove gadget
  exit 0
}

trap dispose SIGTERM SIGINT EXIT

mount_gadget

sleep infinity
dispose