subpackage:
  - runtime*
name: bsd+libbsd-rpi64
version: 0.12.2
$version: 0.12.2
distribution: raspberry/
maintainer:
  name: Mathieu Schroeter
  email: schroeter@epsitec.ch
architecture:
  - source
description:
  brief: This library provides useful functions commonly found on BSD systems
  long: ''
dependency:
  install:
    hadrons+libmd-rpi64:
      - version: ''
        architecture: []
  build:
    xcraft+peon:
      - version: ''
        architecture: []
    xcraft+build-essential:
      - version: ''
        architecture: []
    x-aarch64-linux+gnu-gcc-glibc-cross:
      - version: ''
        architecture: []
bump: []
data:
  get:
    uri: 'https://libbsd.freedesktop.org/releases/libbsd-<THIS.$VERSION>.tar.xz'
    mirrors: []
    ref: ''
    $ref: ''
    out: ''
    externals: true
    prepare: ''
  type: src
  configure: |-
    !{bash}
    cd <THIS.DATA.RULES.LOCATION>
      && ./configure --prefix=<PEON.PREFIXDIR>
                     --build=$MACHTYPE
                     --host=aarch64-xcraft-linux-gnu
                     --enable-static
                     --disable-shared
  rules:
    type: make
    location: data/libbsd-<THIS.$VERSION>
    args:
      postinst: ''
      prerm: ''
      makeall: '-j<PEON.CPUS.COUNT>'
      maketest: ''
      makeinstall: 'install'
    test: none
    env:
      CC: aarch64-xcraft-linux-gnu-gcc
  deploy: ''
  env:
    path: []
    other: {}
  embedded: true
  runtime:
    configure: ''
