subpackage:
  - runtime*
  - 'x+bin:linux-aarch64'
name: carnotzet+whispi-gadget-rpi64
version: 0.1.0
$version: 0.1.0
distribution: raspberry/
maintainer:
  name: Mathieu Schroeter
  email: schroeter@epsitec.ch
architecture:
  - source
description:
  brief: Whispi gadget service
  long: ''
dependency:
  build:
    xcraft+base-build:
      - version: ''
        architecture: []
    rustlang+rust:
      - version: ''
        architecture: []
    x-aarch64-linux+gnu-gcc-glibc-cross:
      - version: ''
        architecture: []
  make:
    xcraft+base-make:
      - version: ''
        architecture: []
bump: []
data:
  get:
    uri: ''
    mirrors: []
    ref: ''
    $ref: ''
    out: ''
    externals: false
    prepare: ''
  type: src
  configure: ''
  rules:
    type: script
    location: ''
    args:
      postinst: ''
      prerm: ''
      makeall: ''
      maketest: ''
      makeinstall: ''
    test: none
    env: {}
  deploy: |-
    mkdir('<PEON.INSTALLDIR.X+BIN>/var/log/whispi-gadget');
    cp('<PEON.ASSETS>/sv',          '<PEON.INSTALLDIR.X+BIN>/etc/sv/whispi-gadget');
    cp('<PEON.ASSETS>/postinst',    '<PEON.INSTALLDIR.X+BIN>/WPKG/postinst');
    cp('<PEON.ASSETS>/prerm',       '<PEON.INSTALLDIR.X+BIN>/WPKG/prerm');
  env:
    path: []
    other: {}
  embedded: true
  runtime:
    configure: ''
