subpackage:
  - runtime*
  - 'x+bin:linux-aarch64'
name: ffmpeg+ffmpeg-rpi64
version: 8.1.2
$version: 8.1.2
distribution: raspberry/
maintainer:
  name: Mathieu Schroeter
  email: schroeter@epsitec.ch
architecture:
  - source
description:
  brief: 'A complete, cross-platform solution to record, convert, ...'
  long: ''
dependency: {}
bump: []
data:
  get:
    uri: 'https://ffmpeg.org/releases/ffmpeg-<THIS.$VERSION>.tar.xz'
    mirrors: []
    ref: ''
    $ref: ''
    out: ''
    externals: false
    prepare: ''
  type: src
  configure: |-
    !cd <THIS.DATA.RULES.LOCATION>
      && ./configure --prefix=/usr
                     --cross-prefix=aarch64-xcraft-linux-gnu-
                     --enable-cross-compile
                     --target-os=linux
                     --arch=arm64
                     --pkg-config=pkg-config
                     --enable-gpl
                     --disable-autodetect
                     --disable-htmlpages
                     --disable-podpages
                     --disable-txtpages
  rules:
    type: script
    location: data/ffmpeg-<THIS.$VERSION>
    args:
      postinst: ''
      prerm: ''
      makeall: '!make -j<PEON.CPUS.COUNT>'
      maketest: ''
      makeinstall: |-
        !  make install DESTDIR=<PEON.INSTALLDIR.X+BIN>
        && make install DESTDIR=<PEON.INSTALLDIR>
        && rm -rf <PEON.INSTALLDIR.X+BIN>/usr/include
        && rm -rf <PEON.INSTALLDIR.X+BIN>/usr/lib
        && rm -rf <PEON.INSTALLDIR>/usr/bin
        && find <PEON.INSTALLDIR> -name "*.pc" -exec sed -i 's|prefix=/usr|prefix=<PEON.INSTALLDIR>/usr|g' {} +
        && find <PEON.INSTALLDIR> -name "*.pc" -exec sed -i 's|libdir=/usr|libdir=<PEON.INSTALLDIR>/usr|g' {} +
        && find <PEON.INSTALLDIR> -name "*.pc" -exec sed -i 's|includedir=/usr|includedir=<PEON.INSTALLDIR>/usr|g' {} +
    test: none
    env: {}
  deploy: ''
  env:
    path: []
    other: {}
  embedded: true
  runtime:
    configure: ''
