~ # cat /etc/pipewire/pipewire.conf.d/pipewire.conf 
context.modules = [
  {
    name = libpipewire-module-loopback
    args = {
      node.description = "Bridge: USB gadget stereo to default sink"

      capture.props = {
        node.name = "capture.pi_bridge.from_gadget_playback"
        target.object = "pi.uac2.source.host_playback"
        node.dont-reconnect = false
        audio.position = [ FL FR ]
      }

      playback.props = {
        node.name = "playback.pi_bridge.default_sink"
        node.dont-reconnect = false
        audio.position = [ FL FR ]
      }
    }
  }

  {
    name = libpipewire-module-loopback
    args = {
      node.description = "Bridge: default mic to USB gadget mono"

      capture.props = {
        node.name = "capture.pi_bridge.from_default_mic"
        node.dont-reconnect = false
        audio.position = [ MONO ]
      }

      playback.props = {
        node.name = "playback.pi_bridge.to_gadget_mic"
        target.object = "pi.uac2.sink.host_microphone"
        node.dont-reconnect = false
        stream.dont-remix = true
        audio.position = [ MONO ]
      }
    }
  }
]