#!/bin/sh

rm -rf /var/service/pipewire
ln -sf /etc/sv/pipewire /var/service/pipewire
sv start pipewire || :

rm -rf /var/service/wireplumber
ln -sf /etc/sv/wireplumber /var/service/wireplumber
sv up wireplumber || :
