#!/bin/sh

rm -rf /var/service/pipewire
ln -sf /etc/sv/pipewire /var/service/pipewire

if [ ! -f /var/service/pipewire/down ]; then
  sv start pipewire || :
fi

rm -rf /var/service/wireplumber
ln -sf /etc/sv/wireplumber /var/service/wireplumber

if [ ! -f /var/service/wireplumber/down ]; then
  sv up wireplumber || :
fi
