monitor.alsa.rules = [
  {
    matches = [
      {
        alsa.card_name = "UAC2_Gadget"
        device.profile.name = "stereo-fallback"
        media.class = "Audio/Source"
      }
    ]

    actions = {
      update-props = {
        node.name = "pi.uac2.source.host_playback"
        node.description = "Pi UAC2 Gadget Host Playback"
      }
    }
  }

  {
    matches = [
      {
        alsa.card_name = "UAC2_Gadget"
        device.profile.name = "mono-fallback"
        media.class = "Audio/Sink"
      }
    ]

    actions = {
      update-props = {
        node.name = "pi.uac2.sink.host_microphone"
        node.description = "Pi UAC2 Gadget Host Microphone"
      }
    }
  }
]