subpackage:
  - runtime*
  - 'x+bin:linux-aarch64'
name: malinen+wpa-supplicant-rpi64
version: '2.10'
$version: '2.10'
distribution: raspberry/
maintainer:
  name: Mathieu Schroeter
  email: schroeter@epsitec.ch
architecture:
  - source
description:
  brief: Linux WPA/WPA2/WPA3/IEEE 802.1X Supplicant
  long: 'wpa_supplicant is a WPA Supplicant for Linux, BSD, Mac OS X, and Windows with support for WPA, WPA2 (IEEE 802.10i / RSN), and WPA3. It is suitable for both desktop/laptop computers and embedded systems. Supplicant is the IEEE 802.1X/WPA component that is used in the client stations. It implements key negotiation with a WPA Authenticator and it controls the roaming and IEEE 802.11 authentication/association of the wlan driver.'
dependency:
  install:
    openssl+openssl3-rpi64-x+bin:
      - version: ''
        architecture: []
        subpackage:
          - x+bin
    openssl+openssl3-rpi64:
      - version: ''
        architecture: []
    thom311+libnl-rpi64:
      - version: ''
        architecture: []
  build:
    xcraft+peon:
      - version: ''
        architecture: []
    xcraft+build-essential:
      - version: ''
        architecture: []
    x-aarch64-linux+gnu-gcc-glibc-cross:
      - version: ''
        architecture: []
bump:
  - carnotzet+os-rpi4b
  - carnotzet+os-rpiz2w
  - carnotzet+rescuefs-rpi4b
  - carnotzet+rescuefs-rpiz2w
data:
  get:
    uri: 'https://w1.fi/releases/wpa_supplicant-<THIS.$VERSION>.tar.gz'
    mirrors: []
    ref: ''
    $ref: ''
    out: ''
    externals: true
    prepare: ''
  type: src
  configure: '!cd <THIS.DATA.RULES.LOCATION> && cp <PEON.ASSETS>/defconfig .config'
  rules:
    type: script
    location: data/wpa_supplicant-<THIS.$VERSION>/wpa_supplicant
    args:
      postinst: ''
      prerm: ''
      makeall: '!make -j<PEON.CPUS.COUNT> BINDIR=/usr/sbin'
      maketest: ''
      makeinstall: '!make install BINDIR=/usr/sbin DESTDIR=<PEON.INSTALLDIR.X+BIN>'
    test: none
    env:
      CC: aarch64-xcraft-linux-gnu-gcc
  deploy: ''
  env:
    path: []
    other: {}
  embedded: true
  runtime:
    configure: ''
