#!/bin/sh

# keep going even if the session is gone (like broken ssh after glibc change)
trap '' HUP

echo "running id: $(id)" | logger -t carnotzet_upgrade

wpkg_upgrade() {
  local result=1
  local log="/tmp/carnotzet_upgrade.log"

  if (wpkg --update >"$log" 2>&1) && \
     (wpkg --upgrade >"$log" 2>&1) && \
     (wpkg --autoremove >"$log" 2>&1)
  then
    result=0
  fi

  cat "$log" | logger -t carnotzet_upgrade
  rm -rf "$log"

  return $result
}

if wpkg_upgrade; then
  echo "reboot after upgrade" | logger -t carnotzet_upgrade
  nohup reboot -d 5 &
  exit 0
fi

echo "upgrade error" | logger -t carnotzet_upgrade
exit 1