subpackage:
  - runtime*
  - 'x+bin:linux-aarch64'
name: tytso+e2fsprogs-rpi4b
version: 1.47.3
$version: 1.47.3
distribution: raspberry/
maintainer:
  name: Mathieu Schroeter
  email: schroeter@epsitec.ch
architecture:
  - source
description:
  brief: Ext2/3/4 Filesystem Utilities
  long: It provides the filesystem utilities for use with the ext2 filesystem. It also supports the ext3 and ext4 filesystems.
dependency:
  build:
    xcraft+base-build:
      - version: ''
        architecture: []
    x-aarch64-linux+gnu-gcc-glibc-cross:
      - version: ''
        architecture: []
bump: []
data:
  get:
    uri: 'https://mirrors.edge.kernel.org/pub/linux/kernel/people/tytso/e2fsprogs/v<THIS.$VERSION>/e2fsprogs-<THIS.$VERSION>.tar.gz'
    mirrors: []
    ref: ''
    $ref: ''
    out: ''
    externals: true
    prepare: ''
  type: src
  configure: |-
    !cd <THIS.DATA.RULES.LOCATION>
      && ./configure --prefix=/usr
                     --build=$MACHTYPE
                     --host=aarch64-xcraft-linux-gnu
                     --enable-symlink-install
  rules:
    type: script
    location: data/e2fsprogs-<THIS.$VERSION>
    args:
      postinst: ''
      prerm: ''
      makeall: '!make -j{PEON.CPUS.COUNT}'
      maketest: ''
      makeinstall: '!make install DESTDIR=<PEON.INSTALLDIR.X+BIN>'
    test: none
    env:
      CC: aarch64-xcraft-linux-gnu-gcc
  deploy: ''
  env:
    path: []
    other: {}
  embedded: true
  runtime:
    configure: ''
