#!/bin/sh
exec 2>&1

echo "Start Wireplumber daemon..."

export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/dbus/system_bus_socket
export DBUS_SYSTEM_BUS_ADDRESS=unix:path=/run/dbus/system_bus_socket

exec /usr/bin/wireplumber