subpackage:
  - runtime*
name: thom311+libnl-rpi4b
version: '3.11.0'
$version: '3.11.0'
distribution: raspberry/
maintainer:
  name: Mathieu Schroeter
  email: schroeter@epsitec.ch
architecture:
  - source
description:
  brief: Netlink Protocol Library Suite (libnl)
  long: 'The libnl suite is a collection of libraries providing APIs to netlink protocol based Linux kernel interfaces.'
dependency:
  build:
    xcraft+peon:
      - version: ''
        architecture: []
    xcraft+build-essential:
      - version: ''
        architecture: []
bump: []
data:
  get:
    uri: 'https://github.com/thom311/libnl/releases/download/libnl3_11_0/libnl-<THIS.$VERSION>.tar.gz'
    mirrors: []
    ref: ''
    $ref: ''
    out: ''
    externals: true
    prepare: ''
  type: src
  configure: |-
    !cd <THIS.DATA.RULES.LOCATION>
      && ./configure --prefix=<PEON.PREFIXDIR>
                     --build=$MACHTYPE
                     --host=aarch64-xcraft-linux-gnu
                     --enable-static
                     --disable-shared
  rules:
    type: script
    location: data/libnl-<THIS.$VERSION>
    args:
      postinst: ''
      prerm: ''
      makeall: '!make -j<PEON.CPUS.COUNT>'
      maketest: ''
      makeinstall: '!make install'
    test: none
    env:
      CC: aarch64-xcraft-linux-gnu-gcc
  deploy: ''
  env:
    path: []
    other: {}
  embedded: true
  runtime:
    configure: ''
