#!/bin/sh

if [ -f "/etc/eeprom.conf" ]; then
  NEW_CONF="$(cat "/etc/eeprom.conf")"
  OLD_CONF="$(rpi-eeprom-config)"
  if [ "$OLD_CONF" != "$NEW_CONF" ]; then
    echo "EEPROM config has changed, apply the new one"
    if rpi-eeprom-config --apply "/etc/eeprom.conf"; then
      if [ ! -f /var/.bootstrapped ]; then
        # Reboot is necessary to apply the new EEPROM settings
        touch /var/.reboot
      fi
    fi
  fi
fi
