subpackage:
  - runtime*
  - 'x+bin:linux-aarch64'
name: litech+radvd-rpi64
version: '2.20'
$version: '2.20'
distribution: raspberry/
maintainer:
  name: Mathieu Schroeter
  email: schroeter@epsitec.ch
architecture:
  - source
description:
  brief: Linux IPv6 Router Advertisement Daemon (radvd)
  long: ''
dependency:
  install:
    bsd+libbsd-rpi64:
      - version: ''
        architecture: []
  build:
    xcraft+peon:
      - version: ''
        architecture: []
    xcraft+build-essential:
      - version: ''
        architecture: []
    x-aarch64-linux+gnu-gcc-glibc-cross:
      - version: ''
        architecture: []
bump:
  - carnotzet+os-whispi-rpiz2w
data:
  get:
    uri: 'https://radvd.litech.org/dist/radvd-<THIS.$VERSION>.tar.gz'
    mirrors: []
    ref: ''
    $ref: ''
    out: ''
    externals: true
    prepare: ''
  type: src
  configure: |-
    !{bash}
    cd <THIS.DATA.RULES.LOCATION>
      && ./configure --prefix=/usr
                     --build=$MACHTYPE
                     --host=aarch64-xcraft-linux-gnu
  rules:
    type: make
    location: data/radvd-<THIS.$VERSION>
    args:
      postinst: ''
      prerm: ''
      makeall: '-j<PEON.CPUS.COUNT>'
      maketest: ''
      makeinstall: 'install DESTDIR=<PEON.INSTALLDIR.X+BIN>'
    test: none
    env:
      CC: aarch64-xcraft-linux-gnu-gcc
  deploy: ''
  env:
    path: []
    other: {}
  embedded: true
  runtime:
    configure: ''
