subpackage:
  - runtime*
name: unigw+wpkg
version: 1.0.2-34
$version: 1.0.2
distribution: carnotzet/
maintainer:
  name: Mathieu Schroeter
  email: schroeter@epsitec.ch
architecture:
  - source
description:
  brief: A Unix Packager For MS-Windows Systems
  long: ''
dependency:
  build:
    xcraft+base-build:
      - version: ''
        architecture: []
    xcraft+build-essential:
      - version: ''
        architecture: []
data:
  get:
    uri: 'https://github.com/Xcraft-Inc/wpkg/archive/651f36cc29ff9a7c6f48972eb9286490174a742d.tar.gz'
    ref: ''
    out: ''
    externals: true
    prepare: ''
  type: src
  configure: |-
    !mkdir -p <THIS.DATA.RULES.LOCATION>
      && mkdir -p <THIS.DATA.RULES.LOCATION>/../wpkg/controlled_vars/build
      && cd <THIS.DATA.RULES.LOCATION>/../wpkg/controlled_vars/build
      && cmake ..
      && make
      && cd -
      && cd <THIS.DATA.RULES.LOCATION>
      && cmake -G "Unix Makefiles" ..
      && cp ../wpkg/controlled_vars/build/controlled_vars ./controlled_vars
  rules:
    type: script
    location: data/wpkg-651f36cc29ff9a7c6f48972eb9286490174a742d/build
    args:
      postinst: ''
      prerm: ''
      makeall: |-
        !export PATH="$(pwd):$PATH"
          && make -j<PEON.CPUS.COUNT>
      maketest: ''
      makeinstall: 'cp("wpkg-Release/tools/wpkg_static", "<PEON.INSTALLDIR>/var/linux/rootfs/usr/bin/wpkg_static");'
    test: none
  deploy: ''
  env:
    path: []
    other: {}
  embedded: true
  runtime:
    configure: ''
