#!/bin/sh

chmod 1777 /tmp

if id rasp >/dev/null 2>&1 && [ ! -d /home/rasp ]; then
  mkdir -p /home/rasp
  chown -R rasp:rasp /home/rasp
fi

mkdir -p /var/lib/wpkg/core/hooks
cp -f /usr/share/wpkg/hooks/core_preinst /var/lib/wpkg/core/hooks/core_preinst
cp -f /usr/share/wpkg/hooks/core_postinst /var/lib/wpkg/core/hooks/core_postinst

ln -sf /etc/sv/network /var/service/network
ln -sf /etc/sv/wifi    /var/service/wifi
ln -sf /etc/sv/ntpd    /var/service/ntpd