subpackage:
  - runtime*
  - srcmod
  - 'x+bin:linux-aarch64'
name: hailo-ai+hailort-drivers-rpi64
version: 5.3.0
$version: 5.3.0
distribution: raspberry/
maintainer:
  name: Mathieu Schroeter
  email: schroeter@epsitec.ch
architecture:
  - source
description:
  brief: Hailo PCIe driver
  long: The Hailo PCIe driver is required for interacting with a Hailo device over the PCIe interface
dependency:
  build:
    xcraft+base-build:
      - version: ''
        architecture: []
    rustlang+rust:
      - version: ''
        architecture: []
    x-aarch64-linux+gnu-gcc-glibc-cross:
      - version: ''
        architecture: []
    gnu+wget:
      - version: ''
        architecture: []
  make:
    xcraft+base-make:
      - version: ''
        architecture: []
bump: []
data:
  get:
    uri: 'https://github.com/hailo-ai/hailort-drivers/archive/refs/tags/v<THIS.$VERSION>.tar.gz'
    mirrors: []
    ref: ''
    $ref: ''
    out: ''
    externals: false
    prepare: ''
  type: src
  configure: ''
  rules:
    type: script
    location: data/hailort-drivers-<THIS.$VERSION>
    args:
      postinst: ''
      prerm: ''
      makeall: |-
        yield exec('bash', '-c', 'patch -p1 < <PEON.ASSETS>/001_fix-newer-kernel.patch');
        cp('.', '<PEON.INSTALLDIR.SRCMOD>/usr/src/hailort-drivers-module-<THIS.$VERSION>-src');
      maketest: ''
      makeinstall: |-
        !   ./download_firmware_hailo10h.sh
         && mkdir -p <PEON.INSTALLDIR.X+BIN>/lib/firmware/hailo
         && mv hailo10h_fw_<THIS.$VERSION> <PEON.INSTALLDIR.X+BIN>/lib/firmware/hailo/hailo10h.<THIS.$VERSION>
         && ln -s /lib/firmware/hailo/hailo10h.<THIS.$VERSION> <PEON.INSTALLDIR.X+BIN>/lib/firmware/hailo/hailo10h
    test: none
    env: {}
  deploy: ''
  env:
    path: []
    other: {}
  embedded: true
  runtime:
    configure: ''
