#!/bin/sh

adduser httpd -SH 2>/dev/null || true

if [ ! -f /var/httpd/www/redirect.html ]; then
  mkdir -p /var/httpd/www
  cp -r /usr/share/httpd/www /var/httpd/
  chown -R httpd /var/httpd/www
fi

rm -rf /var/service/httpd
ln -sf /etc/sv/httpd /var/service/httpd

if [ ! -f /var/service/httpd/down ]; then
  sv up httpd || :
fi
