#!/bin/sh

adduser httpd -SH 2>/dev/null || true

if [ ! -f /var/httpd/www/redirect.html ]; then
  mkdir -p /var/httpd
  cp -r /usr/share/httpd/www /var/httpd/www
  chown -R httpd /var/httpd/www
fi

ln -sf /etc/sv/httpd /var/service/httpd
sv up httpd || :