# Basic mdev.conf configuration
# Device            User:Group    Perms   Action

# Null and zero devices  
null                root:root     666
zero                root:root     666
random              root:root     444
urandom             root:root     444

tty                 root:root     666

SUBSYSTEM=sound;.*  root:audio    666 *[ -x /usr/bin/udev0-helper ] && /usr/bin/udev0-helper; \
  (which curl >/dev/null 2>&1 \
  && curl -X POST -H "Accept: application/json" "http://[::]:9000/whispi/reload-audio") &

input/event[0-9]+   root:root     660 @[ -x /usr/sbin/th-cmd ] && th-cmd --socket /var/run/thd.socket --add /dev/$MDEV
input/event[0-9]+   root:root     660 $[ -x /usr/sbin/th-cmd ] && th-cmd --socket /var/run/thd.socket --remove /dev/$MDEV
