subpackage:
  - runtime*
  - 'x+bin:linux-aarch64'
name: harding+autossh-rpi64
version: 1.4g
$version: 1.4g
distribution: raspberry/
maintainer:
  name: Mathieu Schroeter
  email: schroeter@epsitec.ch
architecture:
  - source
description:
  brief: Automatically restart SSH sessions and tunnels
  long: ''
dependency:
  build:
    xcraft+peon:
      - version: ''
        architecture: []
    xcraft+build-essential:
      - version: ''
        architecture: []
    x-aarch64-linux+gnu-gcc-glibc-cross:
      - version: ''
        architecture: []
bump: []
data:
  get:
    uri: 'https://www.harding.motd.ca/autossh/autossh-<THIS.$VERSION>.tgz'
    mirrors: []
    ref: ''
    $ref: ''
    out: ''
    externals: true
    prepare: ''
  type: src
  configure: |-
    !{bash}
    cd <THIS.DATA.RULES.LOCATION>
      && ./configure --prefix=/usr
                     --build=$MACHTYPE
                     --host=aarch64-xcraft-linux-gnu
                     --with-ssh=/usr/bin/ssh
  rules:
    type: make
    location: data/autossh-<THIS.$VERSION>
    args:
      postinst: ''
      prerm: ''
      makeall: '-j<PEON.CPUS.COUNT>'
      maketest: ''
      makeinstall: 'install DESTDIR=<PEON.INSTALLDIR.X+BIN>'
    test: none
    env:
      CC: aarch64-xcraft-linux-gnu-gcc
      CPPFLAGS: -Drpl_malloc=malloc -Drpl_realloc=realloc
  deploy: ''
  env:
    path: []
    other: {}
  embedded: true
  runtime:
    configure: ''
