#!/bin/sh

ssh-keygen -A

adduser sshd -SH 2>/dev/null || true

chown root:root /var/empty/sshd
chmod 755 /var/empty/sshd

rm -rf /var/service/sshd
ln -sf /etc/sv/sshd /var/service/sshd
sv up sshd || :