#!/bin/sh
mount -t proc none /proc
mount -t sysfs none /sys
mount -t debugfs none /sys/kernel/debug

echo /bin/mdev > /proc/sys/kernel/hotplug
mdev -s

mkdir -p /dev/pts
mount -t devpts none /dev/pts # sshd

fsck -a
# Mount all filesystems
mount -a

sysctl -p >/dev/null
syslogd >/dev/null
crond >/dev/null

# Configure swap
if [ -f /swapfile ]; then
  swapon /swapfile
fi

# Import fr-CH keyboard map
busybox loadkmap < /usr/share/kmap/fr_CH.kmap

# Enable loopback
ip addr add 127.0.0.1/8 dev lo
ip link set dev lo up

echo -e "Carnotzet OS booted in $(cut -d' ' -f1 /proc/uptime) seconds\\n"