subpackage:
  - runtime*
  - 'x+bin:linux-aarch64'
name: wertarbyte+triggerhappy-rpi64
version: 0.5.0
$version: 0.5.0
distribution: raspberry/
maintainer:
  name: Mathieu Schroeter
  email: schroeter@epsitec.ch
architecture:
  - source
description:
  brief: A lightweight hotkey daemon
  long: ''
dependency:
  build:
    xcraft+base-build:
      - version: ''
        architecture: []
    x-aarch64-linux+gnu-gcc-glibc-cross:
      - version: ''
        architecture: []
bump: []
data:
  get:
    uri: 'https://github.com/wertarbyte/triggerhappy/archive/refs/tags/release/<THIS.$VERSION>.tar.gz'
    mirrors: []
    ref: ''
    $ref: ''
    out: ''
    externals: true
    prepare: ''
  type: src
  configure: ''
  rules:
    type: make
    location: data/triggerhappy-release-<THIS.$VERSION>
    args:
      postinst: ''
      prerm: ''
      makeall: '-j<PEON.CPUS.COUNT>'
      maketest: ''
      makeinstall: 'install DESTDIR=<PEON.INSTALLDIR.X+BIN>'
    test: none
    env:
      CC: aarch64-xcraft-linux-gnu-gcc
  deploy: |-
    mkdir('<PEON.INSTALLDIR.X+BIN>/var/log/triggerhappy');
    cp('<PEON.ASSETS>/sv',        '<PEON.INSTALLDIR.X+BIN>/etc/sv/triggerhappy');
    cp('<PEON.ASSETS>/postinst',  '<PEON.INSTALLDIR.X+BIN>/WPKG/postinst');
    cp('<PEON.ASSETS>/prerm',     '<PEON.INSTALLDIR.X+BIN>/WPKG/prerm');
    cp('<PEON.ASSETS>/conffiles', '<PEON.INSTALLDIR.X+BIN>/WPKG/conffiles');
    cp('<PEON.ASSETS>/etc',       '<PEON.INSTALLDIR.X+BIN>/etc');
  env:
    path: []
    other: {}
  embedded: true
  runtime:
    configure: ''
